[package]
name = "xrml-xassets-records"
version = "1.0.0"
authors = ["Chainpool <https://www.chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
# ChainX
xr-primitives = { path = "../../../xr-primitives", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../assets", default-features = false }

[dev-dependencies]
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate", branch="chainx-master" }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", branch="chainx-master" }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", branch="chainx-master" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", branch="chainx-master" }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "support/std",
    "system/std",
    "timestamp/std",
    # ChainX
    "xr-primitives/std",
    "xsupport/std",
    "xassets/std",
]
