[package]
name = "substrate-rpc"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
error-chain = "0.12"
jsonrpc-core = "10.0.1"
jsonrpc-pubsub = "10.0.1"
jsonrpc-derive = "10.0.2"
log = "0.4"
parking_lot = "0.7.1"
parity-codec = "3.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1.7"
rustc-hex = "2.0"

lru = "0.1.16"
lazy_static = "1.3.0"

# substrate
client = { package = "substrate-client", git = "https://github.com/chainpool/substrate" }
substrate-executor = { git = "https://github.com/chainpool/substrate" }
network = { package = "substrate-network", git = "https://github.com/chainpool/substrate" }
primitives = { package = "substrate-primitives", git = "https://github.com/chainpool/substrate" }
state_machine = { package = "substrate-state-machine", git = "https://github.com/chainpool/substrate" }
transaction_pool = { package = "substrate-transaction-pool",  git = "https://github.com/chainpool/substrate" }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate" }
runtime_version = { package = "sr-version", git = "https://github.com/chainpool/substrate" }
# substrate runtime module
support = { package = "srml-support", git = "https://github.com/chainpool/substrate" }

# chainx
chainx-primitives = { path = "../primitives" }
chainx-runtime = {path = "../runtime"}
# chainx runtime api
runtime-api = {path = "../runtime-api"}
# chainx runtime
xr-primitives = { path = "../xr-primitives" }
# chainx runtime module
xassets = { package = "xrml-xassets-assets", path = "../xrml/xassets/assets" }
xrecords = { package = "xrml-xassets-records", path = "../xrml/xassets/records" }
xprocess = { package = "xrml-xassets-process", path = "../xrml/xassets/process" }
xaccounts = { package = "xrml-xaccounts", path = "../xrml/xaccounts" }
xsession = { package = "xrml-xsession", path = "../xrml/xsession" }
xstaking = { package ="xrml-xmining-staking", path = "../xrml/xmining/staking" }
xtokens = { package = "xrml-xmining-tokens", path = "../xrml/xmining/tokens" }
xsupport = { package = "xrml-xsupport", path = "../xrml/xsupport"  }
xbridge-common = { package = "xrml-xbridge-common", path = "../xrml/xbridge/common" }
xbitcoin = { package = "xrml-xbridge-bitcoin", path = "../xrml/xbridge/bitcoin" }
xspot = { package = "xrml-xdex-spot", path = "../xrml/xdex/spot"  }
xbridge-features = { package = "xrml-xbridge-features", path = "../xrml/xbridge/features" }
xmultisig = { package = "xrml-xmultisig", path = "../xrml/xmultisig" }
xfee_manager = { package = "xrml-xfee-manager", path = "../xrml/xfee/manager" }

# bitcoin
btc-keys = { package = "keys", git = "https://github.com/chainx-org/light-bitcoin" }
btc-ser = { package = "serialization", git = "https://github.com/chainx-org/light-bitcoin" }

[dev-dependencies]
assert_matches = "1.1"
futures = "0.1.17"
test_client = { package = "substrate-test-client", git = "https://github.com/chainpool/substrate" }
consensus = { package = "substrate-consensus-common", git = "https://github.com/chainpool/substrate" }
