[package]
name = "xrml-xfee-manager"
version = "1.0.0"
authors = ["Chainpol <http://www.chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
chainx-primitives = { path = "../../../primitives", default-features = false }
xr-primitives = { path = "../../../xr-primitives", default-features = false }
xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default-features = false }

[dev-dependencies]
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate" }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std = [
    "serde/std",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    # ChainX
    "chainx-primitives/std",
    "xr-primitives/std",
    "xsystem/std",
    "xsupport/std",
    "xaccounts/std",
    "xassets/std",
]
