[package]
name = "xrml-xfisher"
version = "1.0.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
# ChainX
xr-primitives = { path = "../../xr-primitives", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../xaccounts", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../xassets/assets", default-features = false }
xsession = { package = "xrml-xsession", path = "../xsession", default-features = false }
xstaking= { package = "xrml-xmining-staking", path = "../xmining/staking", default-features = false }

[dev-dependencies]
# Substrate

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "substrate-primitives/std",
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    "consensus/std",
    # ChainX
    "xr-primitives/std",
    "xaccounts/std",
    "xsupport/std",
    "xassets/std",
    "xsession/std",
    "xstaking/std",
]
