[package]
name = "xrml-grandpa"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>& Chainpool<chainx.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
substrate-primitives = { git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
fg-primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
finality-tracker = { package = "srml-finality-tracker", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
# ChainX
xsupport = { package = "xrml-xsupport", path = "../xsupport", default-features = false }
xsession = { package = "xrml-xsession", path = "../xsession", default-features = false }

[dev-dependencies]
# Substrate
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", branch="chainx-master" }

[features]
default = ["std"]
std = [
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "substrate-primitives/std",
    "fg-primitives/std",
    "rstd/std",
    "primitives/std",
    "support/std",
    "system/std",
    "consensus/std",
    "finality-tracker/std",
    # ChainX
    "xsupport/std",
    "xsession/std",
]
