[package]
name = "xrml-xcontracts"
version = "2.0.0"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
pwasm-utils = { version = "0.12.0", default-features = false }
codec = { package = "parity-codec", version = "3.3", default-features = false, features = ["derive"] }
parity-wasm = { version = "0.41.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }
primitives = { package = "substrate-primitives", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
sr-primitives = { git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
sandbox = { package = "sr-sandbox", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", branch="chainx-master", default-features = false }

# chainx
xr-primitives = { path = "../../xr-primitives", default-features = false }
xsystem = { package = "xrml-xsystem", path = "../xsystem", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../xassets/assets", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../xaccounts", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../xsupport", default-features = false }

[dev-dependencies]
wabt = "0.9.2"
assert_matches = "1.3.0"
hex-literal = "0.2.1"
hex = "0.3.2"
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", branch="chainx-master" }
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate", branch="chainx-master" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "primitives/std",
    "sr-primitives/std",
    "runtime-io/std",
    "rstd/std",
    "sandbox/std",
    "support/std",
    "system/std",
    "parity-wasm/std",
    "pwasm-utils/std",
    "wasmi-validation/std",
    # chainx
    "xr-primitives/std",
    "xsystem/std",
    "xassets/std",
    "xaccounts/std",
    "xsupport/std",
]
