[package]
name = "xrml-xbridge-bitcoin"
version = "1.0.1"
authors = ["Chainpool <http://chainx.org>"]
edition = "2018"

[dependencies]
rustc-hex = { version = "2.0.1", optional = true }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
# Substrate
rstd = { package = "sr-std", git = "https://github.com/chainpool/substrate", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/chainpool/substrate", default-features = false }
substrate-primitives = { git = "https://github.com/chainpool/substrate", default-features = false }
primitives = { package = "sr-primitives", git = "https://github.com/chainpool/substrate", default-features = false }
support = { package = "srml-support", git = "https://github.com/chainpool/substrate", default-features = false }
system = { package = "srml-system", git = "https://github.com/chainpool/substrate", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/chainpool/substrate", default-features = false }
# ChainX
xr-primitives = { path = "../../../xr-primitives", default-features = false }
xsystem = { package = "xrml-xsystem", path = "../../xsystem", default-features = false }
xsupport = { package = "xrml-xsupport", path = "../../xsupport", default-features = false }
xassets = { package = "xrml-xassets-assets", path = "../../xassets/assets", default-features = false }
xrecords = { package = "xrml-xassets-records", path = "../../xassets/records", default-features = false }
xaccounts = { package = "xrml-xaccounts", path = "../../xaccounts", default-features = false }
xfee-manager = { package = "xrml-xfee-manager", path = "../../xfee/manager", default-features = false }
xbridge-common = {package = "xrml-xbridge-common", path = "../common", default-features = false }
# light-bitcoin
btc-primitives = { package = "primitives", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-ser = { package = "serialization", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
merkle = { git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-crypto = { package = "crypto", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-chain = { package = "chain", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-keys = { package = "keys", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }
btc-script = { package = "script", git = "https://github.com/chainx-org/light-bitcoin", default-features = false }

[dev-dependencies]
hex-literal = "0.2"
# Substrate
consensus = { package = "srml-consensus", git = "https://github.com/chainpool/substrate" }

[features]
default = ["std"]
std = [
    "rustc-hex",
    "serde/std",
    "serde_derive",
    "parity-codec/std",
    # Substrate
    "rstd/std",
    "runtime-io/std",
    "substrate-primitives/std",
    "primitives/std",
    "support/std",
    "system/std",
    "timestamp/std",
    # ChainX
    "xr-primitives/std",
    "xsystem/std",
    "xsupport/std",
    "xassets/std",
    "xrecords/std",
    "xaccounts/std",
    "xfee-manager/std",
    "xbridge-common/std",
    # light-bitcoin
    "btc-primitives/std",
    "btc-ser/std",
    "merkle/std",
    "btc-crypto/std",
    "btc-chain/std",
    "btc-keys/std",
    "btc-script/std",
]
